<!--
 * @Author: xujintai
 * @Date: 2021-01-29 11:01:33
 * @LastEditors: xujintai
 * @LastEditTime: 2021-01-30 14:31:42
 * @Description: file content
 * @FilePath: \CoreCode\ajax\test\_05axios_拦截器.html
-->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>

  <button onclick="getRequest1()">发送请求1</button>
  <button onclick="getRequest2()">发送请求2</button>
  <button onclick="cancelRequest()">取消请求</button>

  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const instance = axios.create({
      baseURL: 'http://127.0.0.1:4000',
      timeout: 3000,
    });

    let cancel

    //请求拦截器
    instance.interceptors.request.use(function (config) {
      //请求前取消未完成的请求
      if (typeof cancel === 'function') {
        cancel('成功取消请求')
      }
      //通过将执行器函数传递到构造函数来创建取消令牌：CancelToken
      config.cancelToken = new axios.CancelToken(function executor(c) {
        cancel = c;
      })
      return config;
    });


    function getRequest1() {
      instance.get('/products1').then(response => {
        //响应结果后将cancel设置null(不能调用)
        cancel = null;
        console.log('products1的成功响应', data, response.data);
      }).catch(error => {
        //请求取消后不能将cancel设置null(影响下一次请求不能被取消)
        if (axios.isCancel(error)) {
          console.log('取消products2的请求', error, error.message);
        } else {
          //响应结果后将cancel设置null(不能调用)
          cancel = null;
          console.log('products2的失败响应', error, error.message);
        }
      })
    }


    function getRequest2() {
      instance.get('/products2').then(response => {
        //响应结果后将cancel设置null(不能调用)
        cancel = null;
        console.log('products2的成功响应', response, response.data);
      }).catch(error => {
        //请求取消后不能将cancel设置null(影响下一次请求不能被取消)
        if (axios.isCancel(error)) {
          console.log('取消products2的请求', error, error.message);
        } else {
          //响应结果后将cancel设置null(不能调用)
          cancel = null;
          console.log('products2的失败响应', error, error.message);
        }
      })
    }

    //取消axios请求(取消axios请求返回的错误对象(虽然也有message)但不是Error类型,Error类型拥有stack)
    function cancelRequest() {
      if (typeof cancel === 'function') {
        cancel('成功取消请求')
      }
    }
  </script>
</body>

</html>